[editor]
color-modes = true
true-color = true
auto-pairs = true

[editor.file-picker]
hidden = true
git-ignore = true

[editor.lsp]
display-messages = true

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", ":w"]
ret = ["move_line_down", "goto_first_nonwhitespace"]

# git
[keys.normal.space.g]
g = ":sh lazygit"
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
d = ":sh git diff -- %{buffer_name}"

# cargo
[keys.normal.space.c]
t = ":sh cargo test"
r = ":sh cargo run"
c = ":sh cargo check"

# hurl
[keys.normal.space.h]
h = ":sh hurl %{buffer_name}"
v = ":sh hurl --verbose %{buffer_name}"

# buf path
[keys.normal.space.B]
# Macos
f = ":sh realpath %{buffer_name} | pbcopy"
# Linux (wayland)
# p = ":sh realpath '%{buffer_name}' | wl-copy"
